#ifndef INC_3D_SOLID_CFG_H

#define SCREEN_WIDTH 128*6
#define SCREEN_HEIGHT 128*6

#define TILE_RES_X 128
#define TILE_RES_Y 128
#define ENABLE_CULLING
#define Z_BUFFERING

#define INC_3D_SOLID_CFG_H

#endif //INC_3D_SOLID_CFG_H
